CinePreview/CinePreview/Controllers/GenerosController.cs
using CinePreview.Data;
using CinePreview.Data.Entidades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinePreview.Controllers
{
    public class GenerosController : Controller
    {
        private readonly DataContext _context;

        public GenerosController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Generos
                 .ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Genero genero)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(genero);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception exception)
                {
                    ViewBag.Error(exception.Message);
                }
            }
            return View(genero);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Generos == null)
            {
                return NotFound();
            }

            var genero = await _context.Generos.FindAsync(id);
            if (genero == null)
            {
                return NotFound();
            }
            return View(genero);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Genero genero)
        {
            if (id != genero.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genero);
                    await _context.SaveChangesAsync();
                }
                catch (Exception exception)
                {
                    ViewBag.Error(exception.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genero);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Generos == null)
            {
                return NotFound();
            }

            var genero = await _context.Generos
                .FirstOrDefaultAsync(m => m.Id == id);

            if (genero == null)
            {
                return NotFound();
            }

            try
            {
                _context.Generos.Remove(genero);
                await _context.SaveChangesAsync();
            }
            catch
            {
                ViewBag.Error("No se puede borrar el genero porque tiene registros relacionados.");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CinePreview/CinePreview/Controllers/PeliculasController.cs
using CinePreview.Data;
using CinePreview.Data.Entidades;
using CinePreview.Helpers;
using CinePreview.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinePreview.Controllers
{
    public class PeliculasController : Controller
    {
        private readonly DataContext _context;
        private readonly ICombosHelper _combosHelper;

        public PeliculasController(DataContext context, ICombosHelper combosHelper)
        {
            _context = context;
            _combosHelper = combosHelper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Peliculas
                .Include(p => p.Genero)
                .ToListAsync());
        }

        public async Task<IActionResult> Create()
        {
            CrearPeliculaViewModel model = new()
            {
                Generos = await _combosHelper.GetComboGenerosAsync(),
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CrearPeliculaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var genero = await _context.Generos.FindAsync(model.GeneroId);
                if (genero == null)
                {
                    return NotFound();
                }
                Pelicula pelicula = new()
                {
                    Titulo = model.Titulo,
                    Duracion = model.Duracion,
                    Genero = genero,
                    FechaEstreno = model.FechaEstreno,
                };
                try
                {
                    _context.Add(pelicula);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception exception)
                {
                    ViewBag.Error(exception.Message);
                }
            }
            
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Peliculas == null)
            {
                return NotFound();
            }

           

            var pelicula = await _context.Peliculas                                
                .FindAsync(id);

            if (pelicula == null)
            {
                return NotFound();
            }

            

            CrearPeliculaViewModel model = new()
            {
                Id = pelicula.Id,
                Titulo = pelicula.Titulo,
                Duracion = pelicula.Duracion,                                
                FechaEstreno = pelicula.FechaEstreno,
                Generos = await _combosHelper.GetComboGenerosAsync()
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CrearPeliculaViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var genero = await _context.Generos.FindAsync(model.GeneroId);
                    if (genero == null)
                    {
                        return NotFound();
                    }

                    var pelicula = new Pelicula
                    {
                        Id = model.Id,
                        Titulo = model.Titulo,
                        Duracion = model.Duracion,
                        Genero = genero,
                        FechaEstreno = model.FechaEstreno
                    };
                    _context.Update(pelicula);
                    await _context.SaveChangesAsync();
                }
                catch (Exception exception)
                {
                    ViewBag.Error(exception.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            model.Generos = await _combosHelper.GetComboGenerosAsync();
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Peliculas == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Peliculas
                .FirstOrDefaultAsync(m => m.Id == id);

            if (pelicula == null)
            {
                return NotFound();
            }

            try
            {
                _context.Peliculas.Remove(pelicula);
                await _context.SaveChangesAsync();
            }
            catch
            {
                ViewBag.Error("No se puede borrar la categoría porque tiene registros relacionados.");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CinePreview/CinePreview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CinePreview</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CinePreview.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CinePreview</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Peliculas" asp-action="Index">Peliculas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Generos" asp-action="Index">Generos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CinePreview - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CinePreview/CinePreview/Views/Shared/_VistaBorrar.cshtml
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-blue-gradient">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estas seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"> No</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete"> Sí</button>
            </div>
        </div>
    </div>
</div>

CinePreview/CinePreview/Views/Shared/_VistaModal.cshtml
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-info">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>